version: "3.8"

services:
  flask-app:
    build: .
    container_name: iss_tracker_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/app/data  # Maps local data directory to the app inside the container
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: iss_tracker_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data  # Persist Redis data locally
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
